name: generate_changelog.yml
on:
  push:
    branches:
      - develop

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: true
      - run: |
          pip install -r .github/scripts/requirements.txt
          mkdir -p changelogs
          NEXT_VERSION=$(echo V$(curl https://api.github.com/repos/nationalarchives/pronom/releases/latest | jq -r '.name | ltrimstr("V") | tonumber + 1'))
          python .github/scripts/append_to_changelog.py $NEXT_VERSION
          git add changelogs | true
          git commit -m "Update changelog $NEXT_VERSION" | true
          git push -u origin develop
