name: generate_signature_json.yml
on:
  pull_request:
    branches:
      - main
env:
  BRANCH_NAME: signature-json-update-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  generate_signature_json:
    if: github.head_ref == 'develop'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true
      - id: generate_json
        run: python .github/scripts/generate_signature_json.py
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          git config --global user.email 181243999+tna-da-bot@users.noreply.github.com
          git config --global user.name tna-da-bot
          git checkout -b $BRANCH_NAME
          git add signatures.json
          git commit -m "Generate signature json"
          git push origin $BRANCH_NAME
        if: steps.generate_json.outputs.changes == 'True'

