name: Release PRONOM
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    name: Main release test
    environment: prod
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: true
      - run: |
          .github/scripts/create_signature_files.sh --release
          NEXT_VERSION=$(echo V$(curl https://api.github.com/repos/nationalarchives/pronom/releases/latest | jq -r '.name | ltrimstr("V") | tonumber + 1'))
          NEW_SIGNATURE_FILENAME=$(echo DROID_SignatureFile_$NEXT_VERSION.xml)
          mv signature-file.xml $NEW_SIGNATURE_FILENAME
          mv container-signature-file.xml container-signature-$(date +%Y%m%d).xml
          gh release create $NEXT_VERSION $NEW_SIGNATURE_FILENAME container-signature-$(date +%Y%m%d).xml
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Build website
        uses: octokit/request-action@b91aabaa861c777dcdb14e2387e30eddf04619ae #v3.0.0
        with:
          ref: main
          route: POST /repos/nationalarchives/pronom-website/actions/workflows/release.yml/dispatches
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}